name: Python application

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt

#      - name: Testing
#        run: |
#          pytest
#          python -m flake8

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: docker buildx
      uses: docker/setup-buildx-action@v3
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker build push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: avkarcr/mexc_bot:latest

  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: ssh comands to deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.CLOUD_HOST }}
            username: ${{ secrets.CLOUD_USER }}
            key: ${{ secrets.CLOUD_SSH_KEY }}
            script: |
              sudo docker stop avkarcr/mexc_bot || true
              sudo docker rm avkarcr/mexc_bot || true
              sudo docker pull avkarcr/mexc_bot:latest
              sudo docker run -d -v ~/mexc_bot/db:/app/DB --name mexc_bot --env-file ~/mexc_bot/.env avkarcr/mexc_bot:latest
              sudo docker image prune -a -f
